### PR TITLE
Address the latency in "IMAGE results arrived" progress indicator

### PR DESCRIPTION
**Pull request by hongyec**
Address the problem in [issue 05](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/205)

### CODE REVIEW

**Comment by jaydeepsingh25** [comment]
After these changes, the Audio "Image Results Arrived" will only be played whenever the server returns Renderings. Incase of any error, the popup will show without any sound indicator. @jeffbl , can you please confirm if this is expected behaviour?

**Comment by hongyec** [comment]
@jeffbl Hi Jeff, could you clarify what do you mean by adding "downloading results" indicator at the old spot to handle the latency in downloading. Currently we still have the downloading sound from the progress bar saying "Progressing data".

**Comment by jeffbl** [comment]
Right, understood. My point was that we say "progressing data" which is very generic. We know when the rendering is complete and the download begins, so the idea would be that instead of just saying "progressing data" all the way through we could change the message to "downloading interpretations", so that we don't keep repeating the same generic message when we have more information that would indicate that it is moving forward and not stuck. But, since the download time is typically extremely short, this won't make any difference most of the time, so I'd be perfectly happy leaving things as they are (subject to @Cybernide 's feedback).

**Comment by jeffbl** [comment]
@Cybernide can weigh in from a user perspective, but my guess is that we have much higher priority things to worry about first.

**Comment by hongyec** [comment]
Hi @Cybernide, could you help to generate an audio saying that: "downloading results".

**Comment by Cybernide** [comment]
I'll get @florian-grond on the downloading results. I'll also get him to make an error sound.

**Comment by jaydeepsingh25** [comment]
As mentioned, since it is low priority enhancement. It can be taken up later and tracked via #215. Since rest of the PR seems fine, I am merging this PR.

**Pull request merged**
